import { Injectable } from '@angular/core';
import { Store } from 'src/app/store/store';
import { environment } from 'src/environments/environment'
@Injectable({
  providedIn: 'root'
})
export class StoreService {
  private stores: Store[] = [];
  private imgFolder: string = environment.imageFolder;
  constructor() {
    this.fillData();
  }
  private fillData() {
    this.stores.push(new Store(1, "American Girl® Bistro", "Visit the American Girl Bistro for a casual dining atmosphere that lets girls be girls.Select from fun appetizers, two - course dinners or rich and creamy choices at the Dessert Counter.Join us for brunch, lunch, dinner or afternoon tea.Plus, there's a special Treat Seat and doll-sized cup and saucer just for her doll. Stop in and dine. Reservations accepted but not required.",
      `${this.imgFolder}img1.jpg`),
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Benihana",Description="At Benihana, it's not just a meal, it's an experience. Enjoy teppanyaki favorites like Hibachi Steak, Chicken and Shrimp, as well as sushi and sashimi.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img2.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Bubba Gump Shrimp Co.",Description="Forrest Gump has decided to get in to the restaurant business to share all of his favorite recipes! Bubba Gump Shrimp Co. highlights a huge selection of shrimp and seafood entrees, and also features options for land lovers.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img3.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Buffalo Wild Wings",Description="Buffalo Wild Wings® is the destination for wing fanatics and sports fans alike and continues to prove to its guests again and again that “You Have to Be Here®” to experience the food, the sports and the fun, energetic atmosphere. Its boldly flavored menu includes boneless wings, specialty burgers and sandwiches, ribs, finger foods, wraps, salads and Naked Tenders®. Hungry yet?",Logo="F:/asks/foodcourtApp/foodcourtApp/App/Images/img4.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Cadillac Ranch",Description="Cadillac Ranch is the premier all-American bar and grill. The nearly 11,000-square-foot space offers guests an authentic, all-American family dining experience in a fun and dynamic environment.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img5.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Cantina #1",Description="From enchiladas and Corona-battered fish tacos to coconut cocktails and frozen-fruit margaritas, Cantina #1 delivers the Mexican getaway you crave in a location convenient to home.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img6.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Cantina Laredo",Description="Cantina Laredo offers a modern take on Mexican dining with made-from-scratch recipes and hand-squeezed, lime juice margaritas. The extensive fresh menu includes traditional Mexican favorites in addition to many choice items such as grilled fish, chicken and steaks complemented by Cantina Laredo’s signature sauces such as chipotle-wine or sautéed artichoke hearts and roasted red bell peppers. Entrées are priced between $14 and $26. Vegetarian and gluten-free menus are available.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img7.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Cedar + Stone, Urban Table",Description="Led by celebrated Executive Chef Everton Clarke and Executive Sous Chef Laura Bartholomew, our menu offers refined, crafted dishes inspired by Minnesota’s natural roots and local culture.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/Images/App/img8.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="CRAVE",Description="CRAVE is a concept that truly delivers on one simple thing, fresh and great tasting food brought to life in a chic, casual atmosphere. Enjoy our open kitchen, grand sushi bar and happy hour.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/Images/App/img9.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Dick's Last Resort",Description="From rug-rats to old farts, from high-class to no-class, from the top of the food chain to the bottom of the barrel, it's fun for all and all in fun for those who dare to enter! Sit back and watch or join in the fun. Dick's has always been known for its outrageous, surly, energetic waitstaff who inflict humor upon our guests. Our atmosphere makes everyone feel like they're temporarily breaking all the rules...and getting away with it.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img10.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="FireLake Grill House + Cocktail Bar",Description="FireLake Grill House & Cocktail Bar features a modern yet comfortable décor, a chic bar area, a craft cocktail list, and deluxe desserts. FireLake has reinvented local dining by capturing the essence of the best that Minnesota has to offer with a farm-to-table concept that incorporates fresh and local produce wherever possible—all with a creative flair and an irresistible presentation. Regionally Grown. Minnesota Inspired. Welcome to FireLake.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img11.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Hard Rock Cafe",Description="Hard Rock is bringing its music, memorabilia and rock n’ roll flair back to Minnesota.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img12.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Hooters",Description="This casual, laid back restaurant features good music, sports on the TV and a great menu that includes seafood, sandwiches, burgers and Hooters famous spicy chicken wings.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img13.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="The Lounge @ House of Comedy",Description="This casual, built-to-suit burger bar adjacent to Rick Bronson’s House of Comedy offers something for all burger tastes including Kobe, turkey, chicken and beef.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img14.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Masu Sushi & Robata",Description="Traditional Japanese cuisine in an upbeat, modern restaurant and bar. Our sustainable offerings throughout our menu features fresh, authentic and traditional Japanese foods. In addition to sushi and robata, our menu includes a substantial selection of noodles including different varieties of udon, soba and ramen.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img15.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Nordstrom Café",Description="We are committed to offering a superior dining experience in each of our 200 restaurants and specialty coffee bars. Featuring fresh, local ingredients, our menus vary by restaurant type, season and region, with all items made from scratch. In all of our locations, you can relax and enjoy great food, drinks and service with a warm welcome.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img16.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Rainforest Cafe",Description="A wild place to shop and eat, our dining safari has something for everyone including seafood, beef, chicken, pasta, pizza and an exciting kids menu.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img17.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Ruby Tuesday",Description="Ruby Tuesday is committed to bringing uncompromising freshness and quality to casual dining, which is obvious with one taste of their unbeatable handcrafted burgers, signature entrees and fresh salad bar.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img18.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="Sky Deck Sports Grille and Lanes",Description="Sky Deck is the new destination at Mall of America featuring Minnesota's most unique bowling experience, an amazing selection of classic and cutting-edge video games, incredible High-def sports viewing and a mouth-watering menu selection of burgers, pizza and more!",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img19.jpg" },
      //  new Store {Id= Guid.NewGuid().ToString(),Name="TiGER SUSHi",Description="A hip, little sushi bar featuring exceptional sushi and sashimi in addition to a full menu of soups, salads, appetizers, sake, beer and wine.",Logo="F:/Tasks/foodcourtApp/foodcourtApp/App/Images/img20.jpg" }
    )
  }
  getData(): Store[] {
    return this.stores;
  }
}
